
name: CI

env:
  HEALTHCHECK_DEV: template-cloudfront.dev.cloud.dex.co
  application_name: "template-cloudfront"

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      setRegion:
        description: 'Set region to deploy:'     
        required: true
        default: 'us-east-1' 
        type: choice
        options:
        - us-east-1
        - sa-east-1
      setEnvironment:
        description: 'Set environment to deploy:'     
        required: true
        default: 'dev' 
        type: choice
        options:
        - prod
        - dev
        - stg  
      appName:
        description: 'Application name:'
        required: true
      emptyBucket:
        description: 'Empty S3 bucket:'     
        required: true
        default: 'false' 
        type: choice
        options:
        - false
        - true

jobs:
  emptyBucket:
    if: ${{ github.event.inputs.emptyBucket == 'true'}} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 1200 #session seconds.
          aws-region: ${{ github.event.inputs.setRegion }}
      
      - name: Empty Bucket
        uses: ygabrielmachado/shared-actions

        with:
          sharedScript: empty-bucket
          env: ${{ github.event.inputs.setEnvironment}}
          application-name: ${{ env.application_name }}
  
  ci:
    if: ${{ github.event.inputs.emptyBucket == 'false'}} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 1200 #session seconds.
          aws-region: ${{ github.event.inputs.setRegion }}
      
      - name: Build app
        run:  ./scripts/build-app.sh ${{ github.event.inputs.setEnvironment}}

      - name: Deploy Action
        uses: ygabrielmachado/shared-actions
        with:
          sharedScript: deploy-cloudfront
          env: ${{ github.event.inputs.setEnvironment}}
          application-name: ${{ github.event.inputs.appName }}
      
      - name: HealthCheck
        uses: ygabrielmachado/shared-actions
        with:
          sharedScript: healthcheck
          env: ${{ github.event.inputs.setEnvironment}}
          